#################################################################
#################################################################
##                                                             ##
##                                                             ##
## Andrea Grandieri andreagrandieri.github.io                  ##
##                                                             ##
##                                                             ##
#################################################################
#################################################################

# Title propagated to the entire site, but within the domain (with consideration of subdomains)
title: Andrea Grandieri

#################################################################

# Specifies the theme in use
theme: just-the-docs

#################################################################

# Path to the logo to be used in the site
# # logo: "PATH"

#################################################################

# SEARCH
# Enable or disable the site search
# Supports true (default) or false
search_enabled: true

# Search settings
search:
  # GRANULARITY
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  # Levels refer to the number of # used in MD for headings
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 3
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 5
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 10
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

#################################################################

# AUX LINKS
# Aux links are placed in the upper right corner of the site and are essentially simple links
# Aux links for the upper right navigation
aux_links:
  "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 384 512\"><path d=\"M223.5 32C100 32 0 132.3 0 256S100 480 223.5 480c60.6 0 115.5-24.2 155.8-63.4c5-4.9 6.3-12.5 3.1-18.7s-10.1-9.7-17-8.5c-9.8 1.7-19.8 2.6-30.1 2.6c-96.9 0-175.5-78.8-175.5-176c0-65.8 36-123.1 89.3-153.3c6.1-3.5 9.2-10.5 7.7-17.3s-7.3-11.9-14.3-12.5c-6.3-.5-12.6-.8-19-.8z\"/></svg>":
    - "javascript:void(0);"

  # # "<button id=\"lightdarkSwitcherButton\" type=\"button\" name=\"button\" class=\"btn\" onclick=\"toggleDarkMode()\"><svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 384 512\"><!--! Font Awesome Pro 6.2.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. --><path d=\"M223.5 32C100 32 0 132.3 0 256S100 480 223.5 480c60.6 0 115.5-24.2 155.8-63.4c5-4.9 6.3-12.5 3.1-18.7s-10.1-9.7-17-8.5c-9.8 1.7-19.8 2.6-30.1 2.6c-96.9 0-175.5-78.8-175.5-176c0-65.8 36-123.1 89.3-153.3c6.1-3.5 9.2-10.5 7.7-17.3s-7.3-11.9-14.3-12.5c-6.3-.5-12.6-.8-19-.8z\"/></svg></button>":
  # #   - "#"

  # # "<button><object data=\"/assets/fa-solid_fa-moon.svg\"></object></button>":
  # #   - "#"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false

#################################################################

# ANCHOR LINKS
# Anchor links in headings (the ###### in MD)
# Heading anchor links appear on hover over h1-h6 tags in page content allowing users to deep link to a particular heading on a page.
# Supports true (default) or false
heading_anchors: true

#################################################################

# FOOTER CONTENT
# It appears at the bottom of every page's main content
# Define the footer content in the _includes/footer_custom.html file

# Footer "Edit this page on GitHub" link text
gh_edit_link: false

#################################################################

# Color scheme supports "light" (default) and "dark"
color_scheme: light

#################################################################

# Google Analytics Tracking (optional) (see Google)
# # ga_tracking: IL_TUO_GA_TRACKING_ID 
# Use GDPR compliant Google Analytics settings (true by default)
# # ga_tracking_anonymize_ip: true 

#################################################################

# COLLECTION OF PAGES (CATEGORIES)
# Folder containing all collections
# # collections_dir: NAME_COLLECTIONS_WRAPPER_FOLDER

# Follow enumerated steps:
# # # FIRST THING TO DO: Define Jekyll collections
# # collections:
# #   # e.g.: Define a collection named "putnamehere", its documents reside in the "_putnamehere" directory
# #   putnamehere:
# #     permalink: "/:collection/:path/"
# #     output: true

# # # SECOND THING TO DO
# # just_the_docs:
# #   # Define which collections are used in just-the-docs
# #   collections:
# #     # Reference the "putnamehere" collection
# #     putnamehere:
# #       # Give the collection a name
# #       name: putnamehere_or_whatnameyouwant
# #       # Exclude the collection from the navigation
# #       # Supports true or false (default)
# #       nav_exclude: false
# #       # Exclude the collection from the search
# #       # Supports true or false (default)
# #       search_exclude: false

#################################################################

# Let specify a custom SCSS file
# # color_scheme: NOME_FILE_SCSS

#################################################################

# Plugins
# # plugins:
  # # - jekyll-redirect-from (DISABILITATO SOLAMENTE TEMPORAMENTE)
  # # - jekyll-last-modified-at
